import LocalizedStrings from 'react-native-localization';

export default {

    str: new LocalizedStrings({
        en: {
            btn_confirm_resend:'Confirm resend',
            confirmation:'Confirmation',
            btn_update:'Update',
            confirm_and_exit:'Confirm & Exit',
            backorder:'Backorder',
            item_on_backorder:'Item on Backorder',
            email:'Email',
            file_restrictions:'Allowed file size upto 2MB. Maximum 5 no of files.',
            send:'Send',
            clear:'Clear',
            file_selected:'File selected',
            files_selected:'Files selected',
            find_file:'Find File',
            attachments:'Attachments',
            hint_input_text_work_order_detail:'Enter work order detail here',
            hint_input_text_subject:'Enter subject here',
            hint_input_text_name:'Enter your name here',
            hint_input_text_email:'Enter your email here',
            hint_input_text_phone:'Enter your phone here',
            hint_input_text_query_comments:'Enter your queries/comments',

            your_query_comments:'Your Queries/Comments',
            ready_to_submit:'Ready to Submit',
            submit:'Submit',
            re_submitted:'Re-submitted',
            re_submit:'Re-submit',
            select:'Select',
            selected:'Selected',
            submitted:'Submitted',
            show_notified_orders:'Error Notified',
            to:'to',
            notified:'Notified',
            notify:'Notify',
            already_notified:'Already Notified',
            reason:'Describe Issue',
            total:'Total Amount',
            dont_have_tracking_facility_for_this_carrier:'Tracking not available at this moment', 
            tracking_link:'Tracking Link',
            back:'Back',
            right_menu_option_settings:'Settings',
            right_menu_option_reset_password:'Reset Password',
            right_menu_option_logout:'Logout',
            
            filtered_records:'Filtered Records',
            filtered:'Filtered',
            sku_details:'SKU Details',
            no_data_found:'No data found',
            status_on:'Status On',
            status:'Status',
            receipient:'Recipient',
            postcode:'Postcode',
            filtered_records: 'Filtered Records',
            filtered: 'Filtered',
            sku_details: 'SKU Details',
            no_data_found: 'No data found',
            status_on: 'Status On',
            status: 'Status',
            receipient: 'Receipient',
            postcode: 'Postcode',

            order_details: 'Order Details',
            inbound_details: 'Inbound Details',
            status_colon: 'Status:',
            bom: 'Bom',
            free: 'Free',
            select_date: 'Select Date',
            confirm: 'Confirm',
            select_payment_type: 'Select payment type',

            retry: 'Retry',
            ok: 'OK',
            username: "Username",
            password: "Password",
            login: "LOGIN",
            forget_password: "Forgot Password",
            remember_me: "Remember Me",
            enter_your_username_or_email: "Enter your username or email",
            reset_password: "Reset Password",
            reset: "Reset",
            reset_your_password: "Reset Your Password",
            login_dialog_title: "Logging in",
            login_dialog_messgae: "Please wait...",
            delivered: 'delivered',
            loading: 'Loading',
            delivered_on_time: 'Delivered on time',
            orders: 'Orders',
            storage: 'Storage',
            stock_receipt: 'Stock Receipt',
            top_five_skus: 'Top 5 SKU\'s',
            pallets: 'Pallets',
            shelves: 'Shelves',
            receipts: 'Receipts',
            skus: 'Skus',
            units: 'Units',
            colon: ':',
            custom_font: 'kioskFont',  // this is custom font name don't remove from here
            custom_font_bold_android:'kioskFontMedium',
            custom_font_italic_android:'kioskFontItalic',
            roboto_font_android:'RobotoRegular',
            roboto_font_bold_android:'RobotoBold',
            roboto_font_black_android:'RobotoBold',
            roboto_font_light_bold_android:'RobotoBold',
            
            custom_font_for_ios: 'Geomanist',      // it is same as kioskFont . it was just edit by client
            full_name: 'Full Name',
            email_address: 'Email Address',
            phone: 'Phone',
            website: 'Website',
            current_password: 'Current Password',
            new_password: 'New Password',
            confirm_password: 'Confirm Password',
            save: 'Save',
            this_week: 'This Week',
            half_month: 'Half Month',
            month: 'Month',
            //Inbound 
            //List
            order_status: 'Order Status',
            supplier_name: "Supplier Name",
            purc_order_no: 'Purc. Order No',
            //Search
            from_date: 'From Date',
            to_date: 'To Date',
            delivery_status: 'Delivery Status',
            //Order
            //Orders
            order_no: "Order No",
            ship_name: "Ship Name",
            delivered_capital_first: "Delivered",
            not_delivered: "Not Delivered",
            resend: 'Resend',
            track_order:'Track Order',
            track_this_order: 'Track this order',
            pod_required: 'POD Required',
            pod_available: 'POD Available',
            report_error: 'Report an Issue',
            notify_details: 'Report an Issue',
            claim_insurance: 'Claim Insurance',
            carrier: 'Carrier',
            customer_name: 'Customer Name',
            customer_address: 'Customer Address',
            item_hash: 'Item#',
            qty_order: 'Qty Order',
            qty_shipped: 'Qty Shipped',
            //Report Packing Error
            item_pick_error: 'Item Pick error',
            select_item: 'Select Item',
            multiple_items_error: 'Multiple Items Error',
            value: 'Value',
            label: 'Label',
            error_description: 'Error Description...',
            cancel: 'Cancel',
            //Order search
            order_hash: 'Order#',
            order_no: 'Order No.',
            item_status: 'Item Status',
            batch_no: 'Batch No.',
            batch_no_hash: 'Batch No#',
            issued_date: 'Issued Date',
            payment_type: 'Payment Type',
            //Billing
            //List
            invoice_no: 'Invoice No',
            due_date: "Due Date",
            pur_amount: 'Amount',
            //Work Order
            current_work_orders: 'Current Work Orders',
            completed_work_orders: 'Completed Work Orders',
            //List
            work_order_no: 'Order No',
            p_desc: "Project Description",
            estimated_price: 'Estimated Price',
            //Track Order
            request_proof_of_delivery: 'Request Proof of Delivery',

            // change password
            change_password: 'Changing Password',
            advanced_search: "Advanced Search",
            name: "Name",
            booking_reference: "Booking Reference",
            npf_reference: "NPF Reference",
            purchase_order: "Purchase Order",
            supplier: "Supplier",
            delivery_date: "Delivery Date",
            booked_date: "Booked Date",
            search: "Search",
            item_code: "Item Code",
            soh: 'SOH',
            quantity: "Quantity",
            description: "Description",
            barcode: "Barcode",
            available_stock: "Available Stock",
            //available_qty: "Available \xa0\xa0\xa0\xa0\xa0Qty",
            available_qty: "Available Qty",
            on_hold: "On Hold",
            quarantine: "Quarantine",
            incoming: "Incoming",
            //allocated_qty_in_current_order:'AQCO',
            allocated_qty_in_current_order: 'Allocated To Cur Odr',
            //aqbo:'AQBO',
            aqbo: 'Allocated To Back Odr',
            hold_quantity: 'Hold Qty',
            //incomming_qty:'Incoming \xa0\xa0\xa0\xa0\xa0Qty',
            incomming_qty: 'Incoming Qty',

            // profile module
            company_name: 'Company Name',
            email_id: 'Email',
            phone_no: 'Phone No',
            skype: 'Skype',
            your_name: 'Your Name',
            country: 'Country',
            city: 'City',
            state: 'State',
            time_zone: 'Time Zone',
            company_description: 'Company Description',
            languages: 'Languages',
            copny_web_url: 'Company website URL',
            twitter: 'Twitter',
            company: 'Company',
            button_save: 'SAVE',
            successfully_updated:'Successfully updated.',

            //Module titles
            title_dashboard: 'Dashboard',
            title_order: 'Order',
            title_inbound: 'Inbound',
            title_inventory: 'Inventory',
            title_work_order: 'Work Order',
            title_setting: 'Settings',
            title_change_password: 'Change Password',
            //navigators
            title_billing: 'Billing',

            //order screens
            select_client: 'Select Client',
            allocated: 'Allocated',
            bom_kit: 'Bom/Kit',

            // Top 5 Sku pop up
            Item_Id: 'Item Id',
            Item_Qty: 'Item Qty',
            total_orders: 'Total Orders',

            valid_phone_no: 'Please enter valid phone no',
            valid_web_site: 'Please enter valid website',

            // Boom list pop up 
            MainItem: 'Main Item',
            MainItemDescription: "Main Item Description",
            Component: 'Component',
            Component_Description: 'Description',
            Component_Quantity: 'Qty',
            Component_Quantity_boom: 'Quantity',

            //Free list pop up
            FreeItemCode: 'Free Item Code',
            FreeItemDescription: 'Description',
            FreeItemId: 'FreeItemId',
            // MinOrderEligQty:'Min. Order Qty for eligibility',
            MinOrderEligQty: 'Eligible Qty',
            tyep_: 'Type',


            // Work Order 
            Subject:'Subject',
            message:'Message',

            //Inventory
            intransit_: 'Intransit',
            damage_: 'Damage',
            returns_: 'Returns',
            dimensions_: 'Dimensions',
            weight_: 'Weight',
            dangerous_: 'Dangerous',

            please_select:'Please select...',
            //Change password
            user_name_: 'User Name',
            old_password_: 'Old Password',
            new_password_: 'New Password',
            confirm_password_: 'Confirm New Password',
            email_: 'Email',
            enter_old_pass: 'Please enter old password',
            enter_new_pass: 'Please enter new password',
            enter_confirm_pass: 'Please enter confirm password',
            confirm_equal_new: "Confirm password must be equal to new password",
            new_pass_length: 'New password length must be less than 11 characters',
            new_pass_length_5: "New password length must be greater than 5 characters",
            correct_old_pass: 'Please enter correct old password',
            user_instrutions_line_on_login:'You need to be an existing NPFulfilment user to log-in',
            //Error Messages
            validation_company_url:"Please enter valid company url",
            valdiation_please_write_www:'Please write www in website url',
            /*  error_session_timed_out_login_again:'Your session is timed out, Please login again.', */
            error_session_timed_out_login_again: 'You logged in on another device. If that was not you, please report to Administrator.',
            server_error_occurred: 'Server error occurred',
            "unable_to_get_client_options": 'Unable to get client options',
            please_enter_reason:'Please describe issue for Item Code : ',
            password_error: "Please enter password",
            "invalid_input": "Invalid input",
            "empty": "required*",
            "min_percentage_error": "Minimum Percentage should be ",
            "min_pcm_percentage_error": "Minimum PCM Percentage should be ",
            "internet_connect_error": "Connection issue, Please check your internet connection.",
            "default_error": "Server not responding, Please try after sometime.",
            "registration_close_msg": "New user registrations have been halted due to ongoing maintenance activity. Ple" +
                "ase try again after some time.",
            "x_board_dropdown_error": "Please select examination board",
            "school_name_error": "Please enter school name",
            "address_error": "Please enter address",
            "branch_error": "Please enter branch",
            "roll_no_error": "Please enter roll no",
            "passing_year_error": "Please enter passing year",
            "invalid_passing_year_error": "Please enter valid passing year",
            "subject_error": "Please enter subject",
            "marks_error": "Please enter marks",
            "invalid_marks_error": "Marks can't be greater than out-of marks",
            "outoff_error": "Please enter out-of marks",
            "confirm_scanned_msg": "*We have pre-filled the details from your scanned documents. Do verify on mark s" +
                "heet section.",
            "save_data_error": "Leaving this page will discard unsaved changes",
            "no_data_found_for_search_criteria": "No data found for search criteria",
            "no_data_found_for_this_criteria": "No data found for this criteria",
            validation_individual_file_type:'Please select valid file format (xls, pdf, txt)',
            validation_individual_file_size:'Please select file size upto 2MB',
            validation_please_do_not_select_duplicate_file:'Please do not select duplicate file',
            validation_individual_valid_file:'Please select valid file, this file is corrupt',
            validation_individual_file_upload:'Please select valid file format (xls, pdf, txt) upto 2 MB',
            validation_more_than_max_no_of_files:'Maximum 5 files can be selected',
            please_select_transactions_between:'Please select transactions between',
            transactions_total_can_be_between:'Transactions total value can be between',
            invalid_payment_amount:'Invalid payment amount',
            cant_connect_to_internet:'Cannot connect to the Internet',
            validation_pls_select_value_from_autocomplete_list:'Please select batch code from autocomplete list',
            validation_pls_enter_email_id:'Please enter your email id',
            validation_pls_enter_valid_contact_no:'Please enter valid contact no',
            validation_pls_enter_query_comments:'Please enter query/comments',
            validation_pls_enter_valid_email_id:'Please enter your valid email id',
            validation_pls_enter_subject:'Please enter Subject',
            validation_pls_enter_message:'Please enter message',
            validation_pls_enter_name:'Please enter your name',
            dialog_title_enter_email:'Please provide your email address to proceed further.',
            dialog_title_enter_email_for_resend:'Please provide your email address to proceed further.',
            validation_pls_select_atleast_one_item_to_report:'Please select atleast one item to report issue',
            first_time_resend_confirm_msg:'You have asked us to resend this order to your customer.\nPlease click the "confirm resend" button to proceed.',
            second_and_other_time_resend_confirm_msg:'You have already resent this order. Are you sure you wish to resend it again?',
            validation_pls_enter_company_name:'Please Enter Company name',
        }
    })
};